config {
    type: "view",
    database: "project-b5514482-febd-4435-998",
    schema: "look_util",
    name: "user_age_groups",
}

SELECT
  id AS user_id,
  -- age,
  CASE
    WHEN age < 20 THEN '10代以下'
    WHEN age < 30 THEN '20代'
    WHEN age < 40 THEN '30代'
    WHEN age < 50 THEN '40代'
    WHEN age < 60 THEN '50代'
    WHEN age < 70 THEN '60代'
    ELSE '70代以上'
  END AS age_group
FROM
  ${ref("look_adapter", "users")} 
